# Generated by Django 4.2.20 on 2025-05-31 13:52

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_items_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(default=shop.models.default_pickup_time),
        ),
    ]
